# Developed by: Nemanja Radojkovic, www.linkedin.com/in/radojkovic
app:
  hello_message: "Hello from the config!"
server:
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  logger_class: fast_guni_app.logging.UnifiedLogger